local devices

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -8,13 +8,14 @@ on:
 
 jobs:
   build:
-    name: Build and Test default scheme using any available iPhone simulator
+    name: Build and Test default scheme
 #    runs-on: macos-latest
     runs-on: self-hosted
     
     strategy:
       matrix:
-        destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11']#, 'platform=macOS']
+#        destination: ['platform=iOS Simulator,OS=13.7,name=iPhone 11','platform=macOS']
+         destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
 
     steps:
       - name: Checkout
@@ -31,18 +32,20 @@ jobs:
         env:
           scheme: ${{ 'default' }}
         run: |
-          #device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
           if [ $scheme = default ]; then scheme=$(cat default); fi
           if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
           xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
+          if [ $? == 0 ]; then echo "Build suceeded"
+          else echo "Build failed" fi
           
       - name: Test
         env:
           scheme: ${{ 'default' }}
         run: |
-          #device=`instruments -s -devices | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}'`
           if [ $scheme = default ]; then scheme=$(cat default); fi
           if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
           file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
           xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
+          if [ $? == 0 ]; then echo "Test suceeded"
+          else echo "Test failed" fi
