Testing github action secrets

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -9,8 +9,8 @@ on:
 jobs:
   build:
     name: Build and Test default scheme
-#    runs-on: macos-latest
-    runs-on: self-hosted
+    runs-on: macos-latest
+    # runs-on: self-hosted
     
     strategy:
       matrix:
@@ -18,34 +18,42 @@ jobs:
          destination: ['platform=iOS Simulator,OS=14.0,name=iPhone 11']
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v2
+      - name: Collect github action secrets
+      - env: 
+        TEST_PASSWORD_1: $secrets.TEST_PASSWORD_1
+
+      - name: Print github action secrets
+        run: |
+          echo $TEST_PASSWORD_1
+
+      # - name: Checkout
+      #   uses: actions/checkout@v2
         
-      - name: Set Default Scheme
-        run: |
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo $default | cat >default
-          echo Using default scheme: $default
+      # - name: Set Default Scheme
+      #   run: |
+      #     scheme_list=$(xcodebuild -list -json | tr -d "\n")
+      #     default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
+      #     echo $default | cat >default
+      #     echo Using default scheme: $default
           
-      - name: Build
-        env:
-          scheme: ${{ 'default' }}
-        run: |
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
-          if [ $? == 0 ]; then echo "Build suceeded"
-          else echo "Build failed" fi
+      # - name: Build
+      #   env:
+      #     scheme: ${{ 'default' }}
+      #   run: |
+      #     if [ $scheme = default ]; then scheme=$(cat default); fi
+      #     if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
+      #     file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
+      #     xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
+      #     if [ $? == 0 ]; then echo "Build suceeded"
+      #     else echo "Build failed" fi
           
-      - name: Test
-        env:
-          scheme: ${{ 'default' }}
-        run: |
-          if [ $scheme = default ]; then scheme=$(cat default); fi
-          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
-          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
-          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
-          if [ $? == 0 ]; then echo "Test suceeded"
-          else echo "Test failed" fi
+      # - name: Test
+      #   env:
+      #     scheme: ${{ 'default' }}
+      #   run: |
+      #     if [ $scheme = default ]; then scheme=$(cat default); fi
+      #     if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
+      #     file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
+      #     xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "$destination"
+      #     if [ $? == 0 ]; then echo "Test suceeded"
+      #     else echo "Test failed" fi
